### ISSUE TITLE
CI Deployment Error

### ISSUE THREAD

**Issue by ravipativenu** [SAP-samples/cloud-sdk-team-calendar#1]
Hi,

I could successfully deploy the final application manually with S4HANA and SFSF.

But automatic deployment using CI gives error:

================================
Finished: FAILURE
The command "docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/workspace -v /tmp -e CASC_JENKINS_CONFIG=/workspace/jenkins.yml -e SCP_USER -e SCP_PW -e BRANCH_NAME=$TRAVIS_BRANCH ppiper/jenkinsfile-runner" exited with 2.
Done. Your build exited with 1.
=================================

Could you please help what could be wrong

Thank you..
Venu

**Comment by marikaner** [comment]
Hey Venu, can you check the logs? Probably some test went wrong or npm audit failed, but this is not visible from the message at the end.

**Comment by marikaner** [comment]
If you did everything according to the documentation, this change could help: https://github.com/SAP-samples/cloud-sdk-team-calendar/commit/e0700a10c6149c1faf16d1ff76fb7f4a2c879fe6
